apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  type: LoadBalancer
  ports:
  - name: "user-service"
    port: 8080
    targetPort: 8080
    nodePort: 31003
  selector:
    app: userservice
