apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  type: NodePort
  ports:
  - name: "product-service"
    port: 8080
    targetPort: 8080
    nodePort: 31002
  selector:
    app: productservice
