apiVersion: v1
kind: Service
metadata:
  name: apicomposerservice
spec:
  type: NodePort
  ports:
  - name: "apicomposer-service"
    port: 8080
    targetPort: 8080
    nodePort: 31003
  selector:
    app: apicomposerservice
