kind: PersistentVolume
apiVersion: v1
metadata:
  name: user-service-war-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/code/microservices_kubernetes_docker/user-service/target/user-service-1.0.war"

